---
name: Main
on:
  push:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: |
          make liquipedia
  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: |
          make test
  deploy:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build
        run: |
          make liquipedia
      - name: Deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          npm ci
          make deploy
  deploy-prod:
    if: github.ref == 'refs/heads/master'
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build
        run: |
          make liquipedia
      - name: Deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          npm ci
          make deploy-prod
