---
name: Main
on:
  push:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: |
          npm ci
      - name: Build
        run: |
          make build
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: |
          npm ci
      - name: Check
        run: |
          make check
      - name: Lint
        run: |
          make lint
      - name: Typescript
        run: |
          make tsc
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: |
          npm ci
      - name: Test
        run: |
          make test
