---
name: Main
on:
  push:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Dependencies
        run: |
          npm ci
      - name: Build
        run: |
          make build
  golint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.48.0
  jslint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: |
          npm ci
      - name: Check
        run: |
          make check
      - name: Typescript
        run: |
          make tsc
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Dependencies
        run: |
          npm ci
      - name: Test
        run: |
          make mocha
          make test
